import FooterBottom from "@/components/FooterBottom";
import FooterTop from "@/components/FooterTop";
import HeaderTop from "@/components/HeaderTop";
import Navbar from "@/components/Navbar/Navbar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function WebsiteLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <header id="header">
        <HeaderTop />
        <Navbar />
      </header>
      <main>{children}</main>
      <footer id="footer">
        <div className="bg-[#31384D] p-4"></div>
        <FooterTop />
        <FooterBottom />
      </footer>
    </div>
  );
}
